
package dev2.pe.gob.segdi.wsiopidetramite.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOTramite", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOTramite {


    /**
     * 
     * @param request
     * @return
     *     returns dev2.pe.gob.segdi.wsiopidetramite.ws.RespuestaCargoTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargoResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.CargoResponse")
    @ResponseWrapper(localName = "cargoResponseResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.CargoResponseResponse")
    public RespuestaCargoTramite cargoResponse(
        @WebParam(name = "request", targetNamespace = "")
        CargoTramite request);

    /**
     * 
     * @param request
     * @return
     *     returns dev2.pe.gob.segdi.wsiopidetramite.ws.RespuestaConsultaTramite
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTramiteResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.ConsultarTramiteResponse")
    @ResponseWrapper(localName = "consultarTramiteResponseResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.ConsultarTramiteResponseResponse")
    public RespuestaConsultaTramite consultarTramiteResponse(
        @WebParam(name = "request", targetNamespace = "")
        ConsultaTramite request)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<dev2.pe.gob.segdi.wsiopidetramite.ws.IoTipoDocumentoTramite>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTipoDocumento", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.GetTipoDocumento")
    @ResponseWrapper(localName = "getTipoDocumentoResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.GetTipoDocumentoResponse")
    public List<IoTipoDocumentoTramite> getTipoDocumento();

    /**
     * 
     * @param request
     * @return
     *     returns dev2.pe.gob.segdi.wsiopidetramite.ws.RespuestaTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recepcionarTramiteResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.RecepcionarTramiteResponse")
    @ResponseWrapper(localName = "recepcionarTramiteResponseResponse", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsiopidetramite.ws.RecepcionarTramiteResponseResponse")
    public RespuestaTramite recepcionarTramiteResponse(
        @WebParam(name = "request", targetNamespace = "")
        RecepcionTramite request);

}
