
package prod2.pe.gob.segdi.wsiopidetramite.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PcmIMgdTramite", targetNamespace = "http://ws.wsiopidetramite.segdi.gob.pe/", wsdlLocation = "https://ws2.pide.gob.pe/services/PcmIMgdTramite?wsdl")
public class PcmIMgdTramite
    extends Service
{

    private final static URL PCMIMGDTRAMITE_WSDL_LOCATION;
    private final static WebServiceException PCMIMGDTRAMITE_EXCEPTION;
    private final static QName PCMIMGDTRAMITE_QNAME = new QName("http://ws.wsiopidetramite.segdi.gob.pe/", "PcmIMgdTramite");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://ws2.pide.gob.pe/services/PcmIMgdTramite?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PCMIMGDTRAMITE_WSDL_LOCATION = url;
        PCMIMGDTRAMITE_EXCEPTION = e;
    }

    public PcmIMgdTramite() {
        super(__getWsdlLocation(), PCMIMGDTRAMITE_QNAME);
    }

    public PcmIMgdTramite(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCMIMGDTRAMITE_QNAME, features);
    }

    public PcmIMgdTramite(URL wsdlLocation) {
        super(wsdlLocation, PCMIMGDTRAMITE_QNAME);
    }

    public PcmIMgdTramite(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCMIMGDTRAMITE_QNAME, features);
    }

    public PcmIMgdTramite(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PcmIMgdTramite(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PcmIMgdTramitePortType
     */
    @WebEndpoint(name = "PcmIMgdTramiteHttpsSoap11Endpoint")
    public PcmIMgdTramitePortType getPcmIMgdTramiteHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://ws.wsiopidetramite.segdi.gob.pe/", "PcmIMgdTramiteHttpsSoap11Endpoint"), PcmIMgdTramitePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PcmIMgdTramitePortType
     */
    @WebEndpoint(name = "PcmIMgdTramiteHttpsSoap11Endpoint")
    public PcmIMgdTramitePortType getPcmIMgdTramiteHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wsiopidetramite.segdi.gob.pe/", "PcmIMgdTramiteHttpsSoap11Endpoint"), PcmIMgdTramitePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCMIMGDTRAMITE_EXCEPTION!= null) {
            throw PCMIMGDTRAMITE_EXCEPTION;
        }
        return PCMIMGDTRAMITE_WSDL_LOCATION;
    }

}
