
package dev2.pe.gob.segdi.wsentidad.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Entidad", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Entidad {


    /**
     * 
     * @param sidcatent
     * @param vipent
     * @return
     *     returns java.util.List<dev2.pe.gob.segdi.wsentidad.ws.EntidadBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaEntidad", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsentidad.ws.GetListaEntidad")
    @ResponseWrapper(localName = "getListaEntidadResponse", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsentidad.ws.GetListaEntidadResponse")
    public List<EntidadBean> getListaEntidad(
        @WebParam(name = "vipent", targetNamespace = "")
        String vipent,
        @WebParam(name = "sidcatent", targetNamespace = "")
        int sidcatent);

    /**
     * 
     * @param vrucent
     * @param vipent
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarEntidad", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsentidad.ws.ValidarEntidad")
    @ResponseWrapper(localName = "validarEntidadResponse", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "dev2.pe.gob.segdi.wsentidad.ws.ValidarEntidadResponse")
    public String validarEntidad(
        @WebParam(name = "vipent", targetNamespace = "")
        String vipent,
        @WebParam(name = "vrucent", targetNamespace = "")
        String vrucent);

}
