
package prod2.pe.gob.segdi.wsentidad.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PcmIMgdEntidadPortType", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PcmIMgdEntidadPortType {


    /**
     * 
     * @param sidcatent
     * @return
     *     returns java.util.List<prod2.pe.gob.segdi.wsentidad.ws.EntidadBean>
     */
    @WebMethod(action = "getListaEntidad")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaEntidad", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "prod2.pe.gob.segdi.wsentidad.ws.GetListaEntidad")
    @ResponseWrapper(localName = "getListaEntidadResponse", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "prod2.pe.gob.segdi.wsentidad.ws.GetListaEntidadResponse")
    public List<EntidadBean> getListaEntidad(
        @WebParam(name = "sidcatent", targetNamespace = "")
        int sidcatent);

    /**
     * 
     * @param vrucent
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "validarEntidad")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarEntidad", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "prod2.pe.gob.segdi.wsentidad.ws.ValidarEntidad")
    @ResponseWrapper(localName = "validarEntidadResponse", targetNamespace = "http://ws.wsentidad.segdi.gob.pe/", className = "prod2.pe.gob.segdi.wsentidad.ws.ValidarEntidadResponse")
    public String validarEntidad(
        @WebParam(name = "vrucent", targetNamespace = "")
        String vrucent);

}
