
package local2.pe.gob.segdi.wsiotramite.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Tramite", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", wsdlLocation = "http://127.0.0.1:8080/wsiotramite/Tramite?wsdl")
public class Tramite_Service
    extends Service
{

    private final static URL TRAMITE_WSDL_LOCATION;
    private final static WebServiceException TRAMITE_EXCEPTION;
    private final static QName TRAMITE_QNAME = new QName("http://ws.wsiotramite.segdi.gob.pe/", "Tramite");

    static {
        URL url = null;
        WebServiceException e = null;
        url = Tramite_Service.class.getResource("/devlocal/Tramite.xml");
        /*
        try {
            url = new URL("http://127.0.0.1:8080/wsiotramite/Tramite?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        */
        TRAMITE_WSDL_LOCATION = url;
        TRAMITE_EXCEPTION = e;
    }

    public Tramite_Service() {
        super(__getWsdlLocation(), TRAMITE_QNAME);
    }

    public Tramite_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRAMITE_QNAME, features);
    }

    public Tramite_Service(URL wsdlLocation) {
        super(wsdlLocation, TRAMITE_QNAME);
    }

    public Tramite_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRAMITE_QNAME, features);
    }

    public Tramite_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Tramite_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tramite
     */
    @WebEndpoint(name = "TramitePort")
    public Tramite getTramitePort() {
        return super.getPort(new QName("http://ws.wsiotramite.segdi.gob.pe/", "TramitePort"), Tramite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tramite
     */
    @WebEndpoint(name = "TramitePort")
    public Tramite getTramitePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wsiotramite.segdi.gob.pe/", "TramitePort"), Tramite.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRAMITE_EXCEPTION!= null) {
            throw TRAMITE_EXCEPTION;
        }
        return TRAMITE_WSDL_LOCATION;
    }

}
