
package local2.pe.gob.segdi.wsiotramite.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Tramite", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Tramite {


    /**
     * 
     * @param cargoRequest
     * @return
     *     returns local2.pe.gob.segdi.wsiotramite.ws.RespuestaCargoTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargoResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "local2.pe.gob.segdi.wsiotramite.ws.CargoResponse")
    @ResponseWrapper(localName = "cargoResponseResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "local2.pe.gob.segdi.wsiotramite.ws.CargoResponseResponse")
    public RespuestaCargoTramite cargoResponse(
        @WebParam(name = "cargoRequest", targetNamespace = "")
        CargoTramite cargoRequest);

    /**
     * 
     * @param request
     * @return
     *     returns local2.pe.gob.segdi.wsiotramite.ws.RespuestaConsultaTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarTramiteResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "local2.pe.gob.segdi.wsiotramite.ws.ConsultarTramiteResponse")
    @ResponseWrapper(localName = "consultarTramiteResponseResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "local2.pe.gob.segdi.wsiotramite.ws.ConsultarTramiteResponseResponse")
    public RespuestaConsultaTramite consultarTramiteResponse(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param recepcionRequest
     * @return
     *     returns local2.pe.gob.segdi.wsiotramite.ws.RespuestaTramite
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recepcionarTramiteResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "local2.pe.gob.segdi.wsiotramite.ws.RecepcionarTramiteResponse")
    @ResponseWrapper(localName = "recepcionarTramiteResponseResponse", targetNamespace = "http://ws.wsiotramite.segdi.gob.pe/", className = "local2.pe.gob.segdi.wsiotramite.ws.RecepcionarTramiteResponseResponse")
    public RespuestaTramite recepcionarTramiteResponse(
        @WebParam(name = "recepcionRequest", targetNamespace = "")
        RecepcionTramite recepcionRequest);

}
