name: Build WAR File

on:
  push:
    tags:
      - 'v*'  # Run when any tag is pushed that starts with 'v'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write # Permiso para crear releases y subir archivos
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Get the version
      id: get_version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Upload WAR file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: componente-proxy-${{ steps.get_version.outputs.VERSION || 'latest' }}
        path: target/componente-proxy.war
        retention-days: 7
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          target/componente-proxy.war
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Archive build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          target/maven-status/
          target/*.log
        retention-days: 3
